<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin</name>
   <tag></tag>
   <elementGuidId>8b0c3fb0-49fb-4bf6-bbdc-2f0c349f8048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/web\/index\.php\/admin\/viewAdminModule&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/web/index.php/admin/viewAdminModule']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4faea19-d89f-464d-a72c-3a704ccf686a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-main-menu-item</value>
      <webElementGuid>dda78095-49b0-40f8-b48a-f85f17e57a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/web/index.php/admin/viewAdminModule</value>
      <webElementGuid>007139a7-89a0-4bbc-a5da-042ad12ff5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>02f81c18-663b-4f03-8816-f033aa2a88a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-605cde4963e37af8dc5645b668ea621a</value>
      <webElementGuid>198433e4-1b91-41b8-b00f-5ef23bf61a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/web/index.php/admin/viewAdminModule']</value>
      <webElementGuid>8d5fbc0c-53ac-41ba-84af-873b6e96af5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/web/index.php/admin/viewAdminModule']</value>
      <webElementGuid>496f63ea-5a1b-4f8f-ad17-63cb175418bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/web/index.php/admin/viewAdminModule' and (text() = 'Admin' or . = 'Admin')]</value>
      <webElementGuid>7bd25739-0f3b-4e78-af61-6f2c2f2ec3d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
